bind_addr = ":8080"
log_level = "debug"
database_url = "host=localhost port=5433 dbname=WB0 user=myuser password=password sslmode=disable"

nats_cluster_id = "test-cluster"
nats_hostname = "localhost"
